add Admin questions
FidelusAleksander/ghcertified pull request #190
Opened 2024-02-04 22:12 UTC by garysassano

## PR Type

- [x] Adding new question(s)
> **Warning**: We do not support the inclusion of questions directly copied from official GitHub certification exams. Please only submit original questions and content that you have created.
- [ ] Other content changes (updating questions, answers, explanations or study resources)
- [ ] Code changes (non-content)
- [ ] Documentation changes
- [ ] Other

## What's new?

## Related issue(s)

## Screenshots

2024-02-04 22:22 UTC, FidelusAleksander commented
Damn. Well done @garysassano , you're a champion :rocket: 

I will do my best to review this asap. 

Also if anyone studying for GitHub Administration exam wants to review this, leave thumbs up (as I am not experienced in this area)

2024-02-05 11:26 UTC, FidelusAleksander requested changes
I've left quite a few comments / code suggestions

Once **ALL** are addressed please re-request review so I know I can go through these again

Thanks 🚀

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-044.md
> +question: "Which GitHub plans allow organizations to own an unlimited number of public and private repositories with a full feature set on private repositories? (choose two.)"
What is "full feature set" ? 

GitHub Team for example does not include GitHub Advanced Security features for private repositories.

Make this more clear please + a link to what this refers to

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-042.md
> +1. [x] Organization owner
```suggestion
---

> https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization
1. [x] Organization owner
```

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-041.md
> +1. [x] To allow businesses and open-source projects to collaborate across many projects at once with advanced security and administrative features.
```suggestion
---

> https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations#about-organizations
1. [x] To allow businesses and open-source projects to collaborate across many projects at once with advanced security and administrative features.
```

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-043.md
> +1. [x] By creating nested teams that reflect the group's structure, with cascading access permissions and mentions.
```suggestion
---

> https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations#about-organizations
1. [x] By creating nested teams that reflect the group's structure, with cascading access permissions and mentions.
```

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-045.md
> +1. [x] It allows owners to centrally manage policy and billing for multiple organizations.
```suggestion
---

> https://docs.github.com/en/enterprise-cloud@latest/admin/overview/about-github-for-enterprises#about-github-for-enterprises
1. [x] It allows owners to centrally manage policy and billing for multiple organizations.
```

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-046.md
> +
any link to this? it's a very broad question

how about everything that GHAS covers, that surely enhances the `security posture`

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-049.md
> +1. [x] They can create private repositories (if allowed by the organization's settings) and collaborate on any project within the organization.
`and collaborate on any project within the organization.`

Are you sure this is true? If you are invited to an organization you still need to be added to a repository or a team that is invited to a repository.

You dont get access to all repositories by being a member

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-051.md
> +1. [x] Outside collaborators are granted access to specific repositories rather than the entire organization.
Same comment as i put in q49

Members dont have access to all repositories either.

2024-02-05 11:26 UTC, FidelusAleksander commented on content/questions/admin/question-062.md
> +question: "What are the repository roles available in a GitHub organization?"
```suggestion
question: "What are the repository roles available in a GitHub organization? (Choose five.)"
```

2024-02-05 13:32 UTC, garysassano commented on content/questions/admin/question-028.md
> +1. [x] Using Enterprise Managed Users to create and manage user accounts through your IdP
It's a feature of GitHub Enterprise Cloud, but you can use GitHub Connect along with GitHub Enterprise Server.

2024-02-06 13:33 UTC, FidelusAleksander approved these changes
Looks good to me!

Thanks for contributing @garysassano, this makes the 4th and final practice exam finally available!

2024-02-06 13:34 UTC, merged