New questions to Github Actions
FidelusAleksander/ghcertified pull request #237
Opened 2024-06-11 20:08 UTC by dostonhamrakulov

## PR Type

- [ ] Adding new question(s)
> **Warning**: We do not support the inclusion of questions directly copied from official GitHub certification exams. Please only submit original questions and content that you have created.
- [ ] Other content changes (updating questions, answers, explanations or study resources)
- [ ] Code changes (non-content)
- [ ] Documentation changes
- [ ] Other

## What's new?

## Related issue(s)

## Screenshots

2024-06-11 20:10 UTC, dostonhamrakulov commented
Hi @FidelusAleksander ,
I am planning to take GitHub Actions Certification exam and learning it intensively, I hope if you don't mind if I bring more questions and topics here as part of my learning and contributing to this great project

2024-06-12 17:39 UTC, FidelusAleksander requested changes

2024-06-12 17:40 UTC, FidelusAleksander commented
> Hi @FidelusAleksander ,
> I am planning to take GitHub Actions Certification exam and learning it intensively, I hope that you don't mind if I bring more questions and topics here as part of my learning and contributing to this great project

Go ahead! That's the whole idea behind the project 😎🚀

2024-06-12 17:40 UTC, FidelusAleksander commented
> Hi @FidelusAleksander ,
> I am planning to take GitHub Actions Certification exam and learning it intensively, I hope that you don't mind if I bring more questions and topics here as part of my learning and contributing to this great project

Go ahead! That's the whole idea behind the project 😎🚀

2024-06-12 19:55 UTC, dostonhamrakulov commented on content/questions/actions/question-096.md
> +question: "Select a default environment variable that contains the operating system of the runner executing the job?"
Updated

2024-06-12 19:56 UTC, dostonhamrakulov commented on content/questions/actions/question-097.md
> +question: "How does the cache action in GitHub Actions handle a cache miss?"
Updated

2024-06-12 19:56 UTC, dostonhamrakulov commented on content/questions/actions/question-098.md
> +1. [x] use the on: schedule: cron syntax
updated

2024-06-12 20:14 UTC, dostonhamrakulov commented on content/questions/actions/question-101.md
> +1. [x]
Thanks, I have fixed it:
![Uploading Screenshot 2024-06-12 at 22.12.52.png…]()

2024-06-12 20:22 UTC, FidelusAleksander approved these changes
This looks good to merge :+1: 

Thanks for contributing @dostonhamrakulov  :rocket:  !

2024-06-12 20:23 UTC, merged