New questions - GitHub Actions
FidelusAleksander/ghcertified pull request #242
Opened 2024-06-17 22:11 UTC by dostonhamrakulov

## PR Type

- [x] Adding new question(s)
> **Warning**: We do not support the inclusion of questions directly copied from official GitHub certification exams. Please only submit original questions and content that you have created.
- [ ] Other content changes (updating questions, answers, explanations or study resources)
- [ ] Code changes (non-content)
- [ ] Documentation changes
- [ ] Other

## What's new?
New questions to GitHub Actions

## Related issue(s)

## Screenshots

2024-06-18 21:38 UTC, FidelusAleksander requested changes

2024-06-19 06:37 UTC, dostonhamrakulov commented on content/questions/actions/question-111.md
> +question: "Doston wants to be notified when a comment is created on an issue within a GitHub repository. Which event should be used within the configuration?"
updated

2024-06-19 06:37 UTC, dostonhamrakulov commented on content/questions/actions/question-113.md
> +        if: github.repository == 'myorg/my-prod-repo'
updated

2024-06-19 07:46 UTC, FidelusAleksander approved these changes
This looks good to merge :+1: 

Thanks for contributing again @dostonhamrakulov :rocket:  !

2024-06-19 07:46 UTC, merged