correcting the 116th question answer (suppose to be two correct options)
FidelusAleksander/ghcertified pull request #284
Opened 2024-11-29 19:17 UTC by MogahidGaffar

PR Type
 content changes (updating questions, answers, explanations or study resources)

What's new?
This PR corrects the answer for the 116th question, as it previously listed only one correct answer. 
The question now has two correct options.

Screenshots
![Doc](https://github.com/user-attachments/assets/dbfbc55f-53e9-41d3-98ac-d3ee710bce11)

2024-11-29 20:37 UTC, tfsjohan requested changes
Changes looks good, except for a small spelling error.

2024-11-29 20:37 UTC, tfsjohan commented on content/questions/actions/question-116.md
> +question: "When can you delete workflow runs? (selct two)"
There's spelling error in "selct" here.

2024-11-29 20:56 UTC, MogahidGaffar commented on content/questions/actions/question-116.md
> +question: "When can you delete workflow runs? (selct two)"
sorry , now typo corrected

2024-12-01 19:28 UTC, tfsjohan approved these changes

2024-12-01 19:28 UTC, tfsjohan approved these changes

2024-12-01 19:29 UTC, tfsjohan approved these changes

2024-12-01 19:33 UTC, merged

2024-12-01 19:33 UTC, tfsjohan commented
Thanks for your help!

2024-12-01 19:35 UTC, MogahidGaffar commented
my pleasure! 😄

2024-12-01 19:36 UTC, MogahidGaffar commented
By the way, I have earned my GitHub action certification from Microsoft yesterday. Thank you, too. ! 💙